### ISSUE TITLE
Simplify. Comments

### ISSUE THREAD

**Issue by kalverra** [SeanTankGarvey/prj-rev-bwfs-dasmoto#4]
https://github.com/SeanTankGarvey/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L11

Comments to denote large sections of code are highly useful to organizing your code for both yourself and others.

**Comment by SeanTankGarvey** [comment]
Okay, I understand.  I basically included the divs with respective "item" classes because that was how the HTML was done when I inspected the webpage with developer tools; the rest I did based off the spec sheet. Should I have ignored the classes since I didn't do any CSS styling to the div's?
