### ISSUE TITLE
Great! CSS

### ISSUE THREAD

**Issue by kalverra** [SeanTankGarvey/prj-rev-bwfs-dasmoto#5]
https://github.com/SeanTankGarvey/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/index.css#L10

Nice, organized, and condensed CSS. Check here for more ideas to organize. https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines

**Comment by SeanTankGarvey** [comment]
According to that/those standards, you should NOT have whitespace/lines between CSS rules, but I've been told to add whitespace/lines for clarity.. Which is true?

**Comment by SeanTankGarvey** [comment]
Also, it says to leave a blank line at the end of your page/rules but something about using Unix code (\n), so does that mean you just add a blank line with Enter like normal or you type \n at the end of the last line after the curly brace?
