### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by kalverra** [SeanTankGarvey/prj-rev-bwfs-dasmoto#6]
**Grade**: Exceeds Expectations

**Summary**:
Great work here, you have done well to organize things through your use of divs and indentation, making the code much easier for me and others to read, which is extremely helpful out in the development world (though make sure to utilize spacing and comments to really drive this home). You pay attention to detail, keeping your CSS simple without repeating yourself unnecessarily, keep it up!

For future projects, try throwing in your own little bits of style to dress up the site and personalize it. It's good to practice design along with functional code, so use these templates as opportunity to try some things.

**Comment by SeanTankGarvey** [comment]
Thank you. That is (very) helpful. 👍
